### ISSUE TITLE
pause / volume buttons in disable mode 

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRollStudio#9] opened 2015-12-09 15:00 UTC
1) I have observed that pause / volume buttons in disable mode 

![error](https://cloud.githubusercontent.com/assets/13066894/11684494/e6e7a62c-9e97-11e5-99b3-8dd58324fa30.PNG)

**Comment by praveen4565** [comment] 2015-12-11 14:19
@bigtimebuddy , is it possible to know the reason for the above issue?

**Comment by bigtimebuddy** [comment] 2015-12-11 16:50
Does this happen for other games? Are there any errors in the console (button all the way to the right)?

**Comment by praveen4565** [comment] 2015-12-12 09:36
Its replicating in all the applications. I have not seen any error in the console. But if I can access pause button using space bar application  is getting paused and able to resume too.Not using mouse

**Comment by bigtimebuddy** [comment] 2015-12-12 20:01
I believe the problem is that the SpringRoll Studio's Container is out of date. Will do an update soon which should fix the problem. Meanwhile, you can try to use this [container preview application](http://springroll-tc.pbskids.org/container-preview/index.html) but your app must be accessible on a URL on your local machine.

**Comment by bigtimebuddy** [comment] 2015-12-15 21:01
Fixed in [0.2.14](/SpringRoll/SpringRollStudio/releases/tag/0.2.14].

**Closed by bigtimebuddy** 2015-12-15 21:01 UTC
